version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    ports:
      - "${BACKEND_PORT}:5000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    networks:
      - app-network
    profiles: ["backend", "all"]

  front-backoffice:
    build:
      context: ./front-backoffice
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    ports:
      - "${BACKOFFICE_PORT}:5173"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5173/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 600M
    networks:
      - app-network
    profiles: ["frontend", "all"]

  front-mobile:
    build:
      context: ./front-mobile
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    ports:
      - "${EXPO_PORT}:19000"
      - "${EXPO_DEV_PORT}:19001"
      - "${EXPO_DEBUG_PORT}:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=${EXPO_HOSTNAME:-localhost}
    volumes:
      - ./front-mobile:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:19000/status"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - app-network
    profiles: ["mobile", "all"]
    
  mongo:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 1G
    networks:
      - app-network
    profiles: ["backend", "all"]

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - backend
      - front-backoffice
    restart: unless-stopped
    networks:
      - app-network
    profiles: ["proxy", "all"]
    
volumes:
  mongo-data: