version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: unless-stopped

  front-backoffice:
    build:
      context: ./front-backoffice
      dockerfile: Dockerfile
    ports:
      - "${BACKOFFICE_PORT}:80"
    depends_on:
      - backend
    restart: unless-stopped

  front-mobile:
    build:
      context: ./front-mobile
      dockerfile: Dockerfile
    ports:
      - "${EXPO_PORT}:19000"
      - "${EXPO_DEV_PORT}:19001"
      - "${EXPO_DEBUG_PORT}:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
    volumes:
      - ./front-mobile:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    
  mongo:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    
volumes:
  mongo-data: