name: Backend CI/CD to Google Cloud Run

# --- Trigger Conditions ---
on:
  push:
    branches: [ main ] # Deploy when pushing to the main branch
    paths:
      - 'backend/**' # Only run if files in the backend folder change

# --- Environment Variables ---
env:
  GCP_PROJECT_ID: 'cellular-way-454315-f2' # Your GCP Project ID
  GCP_REGION: 'us-central1' # The region where your Cloud Run service is
  CLOUD_RUN_SERVICE_NAME: 'korpor' # The name of your Cloud Run service
  GAR_REPOSITORY: 'korpor-backend-images' # Define Artifact Registry repo name
  IMAGE_NAME: 'backend-service' # Define the image name within the repo
  # Manually construct the full Artifact Registry image path using defined values
  GAR_IMAGE_PATH: us-central1-docker.pkg.dev/cellular-way-454315-f2/korpor-backend-images/backend-service

# --- Concurrency Control ---
# Ensure only one run happens at a time for the main branch push trigger
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# --- Jobs ---
jobs:
  # --- Job 1: Build, Test, and Push Docker image to Artifact Registry ---
  build-and-push-gar:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Set the working directory to your backend folder
        working-directory: ./backend
    permissions:
      contents: read
      # Required for Artifact Registry auth
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        # Ensure this matches the Node.js version your backend needs
        node-version: '18'

    - name: Install dependencies
      # Add --ignore-scripts to prevent root prepare script (husky) from running
      run: npm install --legacy-peer-deps --ignore-scripts

    # --- Optional Linting/Testing Steps ---
    # Uncomment these if you have lint/test scripts in backend/package.json
    # - name: Run Linters
    #   run: npm run lint
    # - name: Run Tests
    #   run: npm test

    # Authenticate Docker to Google Artifact Registry
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image to Artifact Registry
      id: build-push
      uses: docker/build-push-action@v5
      with:
        context: . # Build context root (Monorepo/)
        file: ./backend/Dockerfile # Path relative to context
        push: true
        # Use the Artifact Registry image path
        tags: ${{ env.GAR_IMAGE_PATH }}:${{ github.sha }}
        labels: |
          org.opencontainers.image.source=${{ github.repositoryUrl }}
          org.opencontainers.image.revision=${{ github.sha }}
        # Enable Docker layer caching
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # --- Job 2: Deploy the image to Google Cloud Run ---
  deploy-to-cloud-run:
    needs: build-and-push-gar # Run after building/pushing
    runs-on: ubuntu-latest
    # Permissions needed for GCP auth and deployment
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation

    steps:
    # Authenticate using the same method as the build job
    - name: Authenticate to Google Cloud via SA Key
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.CLOUD_RUN_SERVICE_NAME }}
        region: ${{ env.GCP_REGION }}
        # Deploy the image from Artifact Registry
        image: ${{ env.GAR_IMAGE_PATH }}:${{ github.sha }}

    # Optional: Output the deployed service URL
    - name: Show Deployed URL
      if: success() # Only run if deployment step succeeds
      run: echo "Deployed successfully to ${{ steps.deploy.outputs.url }}"

    # Add step to test the health endpoint
    - name: Test Deployed Service Health Endpoint
      if: success() # Only run if deployment step succeeded
      run: curl --fail --silent --show-error ${{ steps.deploy.outputs.url }}/health